// flow-typed signature: 4128edbfcc942e6efbf754b3eb5cf84d
// flow-typed version: <<STUB>>/fetch_v^1.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch/example/fetchstream' {
  declare module.exports: any;
}

declare module 'fetch/example/fetchurl' {
  declare module.exports: any;
}

declare module 'fetch/example/pipe' {
  declare module.exports: any;
}

declare module 'fetch/Gruntfile' {
  declare module.exports: any;
}

declare module 'fetch/lib/cookiejar' {
  declare module.exports: any;
}

declare module 'fetch/lib/fetch' {
  declare module.exports: any;
}

declare module 'fetch/test/fetch-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch/example/fetchstream.js' {
  declare module.exports: $Exports<'fetch/example/fetchstream'>;
}
declare module 'fetch/example/fetchurl.js' {
  declare module.exports: $Exports<'fetch/example/fetchurl'>;
}
declare module 'fetch/example/pipe.js' {
  declare module.exports: $Exports<'fetch/example/pipe'>;
}
declare module 'fetch/Gruntfile.js' {
  declare module.exports: $Exports<'fetch/Gruntfile'>;
}
declare module 'fetch/lib/cookiejar.js' {
  declare module.exports: $Exports<'fetch/lib/cookiejar'>;
}
declare module 'fetch/lib/fetch.js' {
  declare module.exports: $Exports<'fetch/lib/fetch'>;
}
declare module 'fetch/test/fetch-test.js' {
  declare module.exports: $Exports<'fetch/test/fetch-test'>;
}
