// flow-typed signature: 2c5852380bfcc277e81a7ca7d3eac839
// flow-typed version: <<STUB>>/panda-session_v^0.1.6/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'panda-session'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'panda-session' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'panda-session/src/session' {
  declare module.exports: any;
}

// Filename aliases
declare module 'panda-session/src/session.js' {
  declare module.exports: $Exports<'panda-session/src/session'>;
}
