#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit

echo "Package play jars."

set +x
echo "##teamcity[progressStart 'sbt test and dist']"
set -x

./sbt-tc "project facia-tool" compile debian:packageBin

set +x
echo "##teamcity[progressFinish 'sbt test and dist']"

echo "##teamcity[progressStart 'zipping and publishing']"
set -x

rm -rf "dist"

configurations="facia-tool"


echo "package for facia-tool"

# Generate folder for the application zip.
app_folder="dist/facia-tool"

mkdir -p "$app_folder/packages/frontend-static"
mkdir -p "$app_folder/packages/facia-tool"
cp "facia-tool/conf/deploy.json"                        "$app_folder"
cp "facia-tool/target/facia-tool_0.1-SNAPSHOT_all.deb"  "$app_folder/packages/facia-tool"

pushd $app_folder
zip -r "../artifacts.zip" .
popd

rm -rf $app_folder

set +o xtrace
echo "##teamcity[publishArtifacts 'dist/artifacts.zip']"
set -o xtrace


set +x
echo "##teamcity[progressFinish 'zipping and publishing']"
set -x

echo "Done disting."

