#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit

echo "Dist play jars."

set +x
echo "##teamcity[progressStart 'sbt test and dist']"
set -x

./sbt-tc "project root" compile test assets dist

set +x
echo "##teamcity[progressFinish 'sbt test and dist']"

echo "##teamcity[progressStart 'zipping and publishing']"
set -x

rm -rf "dist"

projects="facia-tool"
dest_project="facia-tool"

for project in $projects
do
    echo "Dist for $project"

    # Generate folder for the application zip.
    app_folder="dist/$dest_project"
    dest_folder="$app_folder/packages/$dest_project"

    mkdir -p "$app_folder/packages/$dest_project"

    mv "$project/target/universal/$project-0.1-SNAPSHOT.zip"  "$dest_folder/$project.zip"
    cp "$project/conf/deploy.json"                            "$app_folder"

    pushd $app_folder
    zip -r "../artifacts.zip" .
    popd

    rm -rf $app_folder

    set +o xtrace
    echo "##teamcity[publishArtifacts 'dist/artifacts.zip']"
    set -o xtrace
done

set +x
echo "##teamcity[progressFinish 'zipping and publishing']"
set -x

echo "Done disting."
