#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit

echo "Npm and JSPM installation."
npm prune --production
npm install

./node_modules/.bin/jspm config registries.github.auth $JSPM_GITHUB_AUTH
./node_modules/.bin/jspm registry export github
./node_modules/.bin/jspm install
