version: '3'

services:
    postgres:
        image: postgres:10.7-alpine
        container_name: facia-tool-postgres
        ports:
            - 4724:5432
        environment:
            - POSTGRES_USER=faciatool
            - POSTGRES_PASSWORD=faciatool
            - POSTGRES_DB=faciatool
        volumes:
            - postgres-data:/var/lib/postgresql/data
        command: [ "postgres", "-c", "log_statement=all", "-N", "500" ]
volumes:
    postgres-data:
        driver: local
