version: '3'

services:
    postgres:
        image: postgres:10.7-alpine
        container_name: facia-tool-postgres
        ports:
            - 4724:5432
        environment:
            - POSTGRES_USER=faciatool
            - POSTGRES_PASSWORD=faciatool
            - POSTGRES_DB=faciatool
        volumes:
            - postgres-data:/var/lib/postgresql/data
        command: [ "postgres", "-c", "log_statement=all", "-N", "500" ]
    localstack:
        image: localstack/localstack:4.9.2
        container_name: facia-tool-localstack
        ports:
            - "4566:4566"
        environment:
            - SERVICES=s3
            - DEFAULT_REGION=eu-west-1
            - PERSISTENCE=1
        volumes:
            - localstack-data:/var/lib/localstack
volumes:
    postgres-data:
        driver: local
    localstack-data:
        driver: local
