#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit

./node_modules/.bin/jspm config registries.github.auth $JSPM_GITHUB_AUTH
./node_modules/.bin/jspm registry export github

grunt --stack --no-color "$@"
