---
AWSTemplateFormatVersion: "2010-09-09"
Description: Facia Tool Service
Parameters:
  Stage:
    Description: Environment name
    Type: String
    AllowedValues:
      - CODE
      - PROD
    Default: PROD
  FrontendRoleToAssume:
    Description: Frontend Role to assume for cross account policies
    Type: String
    Default: arn:aws:iam::642631414762:role/CmsFrontsRole-FaciaToolRole-1U44IWRZDIWAX
  SwitchboardBucket:
    Description: Bucket where switchboard writes switches status
    Type: String
    Default: arn:aws:s3:::facia-switches/*
  FrontendAccountID:
    Description: AWS account ID of frontend
    Type: String
  MobileAPIAccountID:
    Description: AWS account ID of MAPI
    Type: String
  MobileAPITeamcityAccountID:
    Description: AWS account ID of MAPI - used for CI
    Type: String
  OphanAccountID:
    Description: AWS account ID of Ophan
    Type: String
  ContentAPIAccountID:
    Description: AWS account ID of CAPI
    Type: String
  SupportAccountID:
    Description: AWS account ID of Support
    Type: String
  StaticBucketName:
    Description: Bucket containing static files
    Type: String
  CloudFrontCertificateArn:
    Description: x509 certificate ARN for CloudFront - must be in us-east-1
    Type: String
  CapiPreviewRole:
    Type: String
    Description: ARN of the CAPI preview role
  UserDataTablePrefix:
    Type: String
    Default: fronts-user-data-table
  DBSecurityGroupIdNewVPC:
    Type: String
  CapiEndpointSsmKeyNewVPC:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /newvpc/endpoint/capi/PROD
    Description: SSM key containing security group of the CAPI endpoint
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The new VPC we look to migrate to
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The public subnets of the new VPC for the loadbalancer
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The private subnets of the new VPC for the autoscaling group

Mappings:
  StageMap:
    PROD:
      CloudFrontAliases:
        - fronts.gutools.co.uk
      StaticCloudFrontAliases:
        - fronts-static.gutools.co.uk
      LowerCaseStage: prod
    CODE:
      CloudFrontAliases:
        - fronts.code.dev-gutools.co.uk
      StaticCloudFrontAliases:
        - fronts-static.code.dev-gutools.co.uk
      LowerCaseStage: code
  CrossResources:
    CODE:
      FrontPressedTable: front-pressed-lambda-CODE-DynamoDBTable-1CY26GZDUP0OU
    PROD:
      FrontPressedTable: front-pressed-lambda-PROD-DynamoDBTable-M03VC0RYBQ1W

Resources:
  StaticCloudFrontDnsRecord:
    Type: Guardian::DNS::RecordSet
    Properties:
      Name:
        Fn::Select:
          - 0
          - Fn::FindInMap:
            - StageMap
            - Ref: Stage
            - StaticCloudFrontAliases
      ResourceRecords:
      - Fn::Join:
          - ""
          - - !GetAtt StaticCloudfront.DomainName
            - "."
      TTL: 900
      RecordType: CNAME
      Stage: !Ref Stage
  DnsRecord:
    Type: Guardian::DNS::RecordSet
    Properties:
      Name:
        Fn::Select:
          - 0
          - Fn::FindInMap:
            - StageMap
            - Ref: Stage
            - CloudFrontAliases
      ResourceRecords:
      - Fn::Join:
          - ""
          - - !GetAtt FaciaCloudfront.DomainName
            - "."
      TTL: 900
      RecordType: CNAME
      Stage: !Ref Stage

  FrontsUpdateSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS Topic for fronts updates (both draft & live)

  FeastPublicationTopic:
    Type: AWS::SNS::Topic

  FrontsUpdateSNSPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref FrontsUpdateSNSTopic
      PolicyDocument:
        Statement:
          - Sid: MobileAccount
            Effect: Allow
            Principal:
              AWS: !Ref 'MobileAPIAccountID'
            Action: "sns:Subscribe"
            Resource: !Ref 'FrontsUpdateSNSTopic'
          - Sid: FrontendAccount
            Effect: Allow
            Principal:
              AWS: !Ref 'FrontendAccountID'
            Action: "sns:Subscribe"
            Resource: !Ref 'FrontsUpdateSNSTopic'
          - Sid: OphanAccount
            Effect: Allow
            Principal:
              AWS: !Ref 'OphanAccountID'
            Action: "sns:Subscribe"
            Resource: !Ref 'FrontsUpdateSNSTopic'

  StorageConsumerRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:aws:iam::"
                    - Ref: FrontendAccountID
                    - ":root"
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:aws:iam::"
                    - Ref: MobileAPIAccountID
                    - ":root"
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:aws:iam::"
                    - Ref: MobileAPITeamcityAccountID
                    - ":root"
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:aws:iam::"
                    - Ref: OphanAccountID
                    - ":root"
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:aws:iam::"
                    - Ref: ContentAPIAccountID
                    - ":root"
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:aws:iam::"
                    - Ref: SupportAccountID
                    - ":root"
  StorageBucket:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: StorageBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:PutObjectAcl
            Resource:
              - Fn::Join:
                  - ""
                  - - arn:aws:s3:::facia-tool-store/
                    - Ref: Stage
                    - "/*"
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::facia-tool-store
      Roles:
        - Ref: StorageConsumerRole
  FrontsUserDataDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ["-", [Ref: UserDataTablePrefix, Ref: Stage]]
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: devx-backup-enabled
          Value: true

  FaciaCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: http2
        IPV6Enabled: true
        Aliases:
          Fn::FindInMap:
            - StageMap
            - Ref: Stage
            - CloudFrontAliases
        Origins:
          - CustomOriginConfig:
              HTTPSPort: "443"
              OriginProtocolPolicy: https-only
            # Always replaced at synth time with the GuEc2App ALB's DNS name (see cdk/lib/facia-tool.ts).
            DomainName: overridden-by-cdk.invalid
            Id: facia-tool
        DefaultRootObject: v2
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          Compress: true
          ForwardedValues:
            Headers:
              - "*"
            QueryString: true
            Cookies:
              Forward: all
          TargetOriginId: facia-tool
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        Enabled: true
        ViewerCertificate:
          AcmCertificateArn:
            Ref: CloudFrontCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
  StaticCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: http2
        IPV6Enabled: true
        Aliases:
          Fn::FindInMap:
            - StageMap
            - Ref: Stage
            - StaticCloudFrontAliases
        Origins:
          - S3OriginConfig:
              OriginAccessIdentity: ""
            DomainName:
              Fn::Join:
                - ""
                - - Ref: StaticBucketName
                  - .s3.amazonaws.com
            Id: static-facia-tool
            OriginPath:
              Fn::Join:
                - ""
                - - /
                  - Ref: Stage
                  - /static-facia-tool
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: static-facia-tool
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        Enabled: true
        ViewerCertificate:
          AcmCertificateArn:
            Ref: CloudFrontCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

  RunFaciaToolLocally:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsCode
    Properties:
      Description: Policy used for running fronts-tool locally
      Path: !Sub "/developer-policy/guardian/facia-tool/cms-fronts/${Stage}/run-fronts-tool-locally/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: ssm:GetParameter
            Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/facia-tool/cms-fronts/${Stage}/*"
          - Effect: Allow
            Action: kms:Decrypt
            Resource:
              - !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/alias/aws/ssm"
          - Effect: Allow
            Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            Resource:
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:publish-events-${Stage}"
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - !Sub "arn:aws:s3:::facia-dist/${Stage}/*"
              - !Sub "arn:aws:s3:::facia-private/facia-tool.application.secrets.local.conf"
              - !Sub "arn:aws:s3:::facia-private/facia-tool.local.properties"
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:Scan
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${FrontsUserDataDynamoTable}"
          - Effect: Allow
            Resource: "*"
            Action:
              - ec2:DescribeTags
              - ec2:DescribeInstances
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribeAutoScalingInstances
              - rds:DescribeDBInstances
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              - Fn::Sub:
                - arn:aws:s3:::published-editions-${LowerCaseStage}/*
                - LowerCaseStage: !FindInMap [ StageMap, Ref: Stage, LowerCaseStage ]
              - Fn::Sub:
                - arn:aws:s3:::preview-editions-${LowerCaseStage}/*
                - LowerCaseStage: !FindInMap [ StageMap, Ref: Stage, LowerCaseStage ]
          - Sid: AllowPublishToMyTopic
            Effect: Allow
            Action: sns:Publish
            Resource: !Ref 'FrontsUpdateSNSTopic'
          - Effect: Allow
            Action: sns:Publish
            Resource: !Ref FeastPublicationTopic
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:PutObjectAcl
            Resource:
              - !Sub "arn:aws:s3:::facia-tool-store/${Stage}/*"
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::facia-tool-store
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - arn:aws:s3:::pan-domain-auth-settings/local.dev-gutools.co.uk.settings
              - arn:aws:s3:::pan-domain-auth-settings/local.dev-gutools.co.uk.settings.public
              - arn:aws:s3:::pan-domain-auth-settings/*.p12
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - !Sub "arn:aws:s3:::permissions-cache/${Stage}/*"
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              Ref: CapiPreviewRole
          - Effect: Allow
            Action: s3:GetObject
            Resource:
              Ref: SwitchboardBucket
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
            Resource:
              - Fn::Sub:
                - "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Table}"
                - Table: !FindInMap [ CrossResources, !Ref Stage, FrontPressedTable ]

Conditions:
  IsCode: !Equals [ !Ref Stage, CODE ]

Outputs:
  StorageConsumerRole:
    Description: Role to be assumed for cross account access to the bucket
    Value:
      Ref: StorageConsumerRole
  FrontsUpdateSNSTopicARN:
    Description: ARN of the SNS topic
    Value:
      Ref: FrontsUpdateSNSTopic
    Export:
      Name: !Sub "${AWS::StackName}-FrontsUpdateSNSTopicARN"
  FeastPublicationSNSTopic:
    Description: ARN of the SNS topic
    Value:
      Ref: FeastPublicationTopic
    Export:
      Name: !Sub "${AWS::StackName}-FeastPublicationSNSTopicARN"
