db.default {
    hostname = localhost
    username = faciatool
    password = faciatool
    port = 4724
}

# Uncomment to use localstack for S3 in development
#
# aws {
#     frontsBucket: "facia-tool-store-local"
#     localS3Endpoint: "http://localhost:4566"
# }
