name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      SKIP_NODE: false
      ORG: guardian
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
