# This action submits a report to snyk on every push

name: Snyk
on:
  push:
    branches:
      - main
      - nt/snyk
  workflow_dispatch:


jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      ORG: guardian-test
      JAVA_VERSION: 8
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
