# This action submits a report to snyk on every push

name: Snyk
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  snyk-V2-and-scala:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      ORG: guardian
      JAVA_VERSION: 8
      EXCLUDE: package-lock.json # exclude V1, since it has its own special job below (because of JSPM)
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  snyk-V1-only:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      ORG: guardian
      JAVA_VERSION: 8
      EXCLUDE: fronts-client # exclude V2, since it's captured by the main job above
      SKIP_SBT: true # exclude scala, since it's captured by the main job above
      NODE_PACKAGE_JSON_FILES_MISSING_LOCK: v1_jspm_snyk_workaround/package.json v1_jspm_snyk_workaround/result/package.json
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
